ci(release): 更新 release.yml 和 release_message.md
- 移除了 release_message.md 中的平台下载提示
- 在 release.yml 中:
  - 注释掉了无法获取 github.ref_name 的 TAG_NAME 变量
  - 引入了当前标签名称作为 TAG_NAME
  - 更新了 release.md 文件中的版本替换逻辑
  - 注释掉了 gitchangelog 命令，可能是因为不需要或有问题

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,7 +18,7 @@ on:
   #       default: "draft"
 env:
   ENV_A: 1
-  TAG_NAME: "${{ github.ref_name }}"
+  # TAG_NAME: "${{ github.ref_name }}" # 这里无法获取 github.ref_name
   # FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
 
 jobs:
@@ -163,12 +163,12 @@ jobs:
       - name: Prepare release message
         run: |
           pip install gitchangelog pystache mustache markdown
-          prelease=$(curl --silent "https://api.github.com/repos/jeffid/flutter_ci/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
-          current="${{ env.TAG_NAME }}"
-          sed -e "s|RELEASE_TAG|${{ env.TAG_NAME }}|g" -e "s|VERSION|${VERSION}|g" ./.github/release_message.md > release.md
-          echo -e "\n\n<details markdown=1> <summary>All changes from $current to the latest commit:</summary>\n\n" >> release.md
-          gitchangelog
-          gitchangelog "${prelease}.." >> release.md  2>&1 || echo "Error in gitchangelog"
+          # prelease=$(curl --silent "https://api.github.com/repos/jeffid/flutter_ci/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')
+          TAG_NAME="${{ github.ref_name }}"
+          sed -e "s|RELEASE_TAG|${TAG_NAME}|g" -e "s|VERSION|${VERSION}|g" ./.github/release_message.md > release.md
+          echo -e "\n\n<details markdown=1> <summary>All changes from $TAG_NAME to the latest commit:</summary>\n\n" >> release.md
+          # gitchangelog
+          gitchangelog >> release.md  2>&1 || echo "Error in gitchangelog"
           echo -e "\n\n</details>" >> release.md
       - name: Release app
         uses: ncipollo/release-action@v1
